### ISSUE TITLE
Just installed Legato v1.0 via Mac dmg file. Getting an Error while scanning projects message.

### ISSUE THREAD

**Issue by jonahgabriel** [pruizlezcano/legato#36]
## Prerequisites

- [x] Using the latest version of [Legato](https://github.com/pruizlezcano/legato/releases/latest)

## Expected Behavior
I expected the app to work.

## Current Behavior
I get an error: 

Error while scanning projects
incorrect header check

## Steps to Reproduce

1. It happens every time I scan.

## Your Environment

- Operating System and version: Mac OS 14.3.1
- Ableton version: Ableton 12 Suite

<img width="1136" alt="Screenshot 2024-03-14 at 5 50 47 PM" src="https://github.com/pruizlezcano/legato/assets/1002253/43060aef-8179-45a6-99b2-1e07d7ab6268">

**Comment by pruizlezcano** [comment]
Should be fixed in the new release
